生成されるサーバーのテストコードを修正
frouriojs/create-frourio-app pull request #263
Opened 2021-09-04 11:14 UTC by IshinoJun

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Issue Number: [258](https://github.com/frouriojs/create-frourio-app/issues/258)

2021-10-04 11:09 UTC, LumaKernel commented
Sorry for late review.

2021-10-04 11:19 UTC, LumaKernel requested changes

2021-10-04 11:19 UTC, LumaKernel commented on server/templates/@testing=jest/server/test/server.test.ts
> +  expect(res.status).toBe(200)
関連の issue を読みましたが、これが問題を解決しているのか疑問です。
expect(...).toBe は [type assertion (`: asserts T`)](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html) をしないので、特に型情報への影響を与えていないかと思います。
まずテストが落ちる状況があるはずなのでそこにいきついて、(アップデートかな？ごめんなさい、詳細わからず)
そして `assert(res.status === 200, 'response status code should be 200')` などとするのかなと思います。( Node.js 標準の `assert` は `: asserts T` を使っていて、jest は `assert` の使用をサポートしています )
もしくはもとの issue にある `fail` はおそらく `assert.fail` のことかな？なのでこれもありかもです。

2021-10-10 11:04 UTC, IshinoJun commented
最新のfrourio（0.25.1）でも再現できますね。

2021-10-10 11:28 UTC, LumaKernel commented
ok

2022-01-12 04:22 UTC, hashue approved these changes

2022-02-06 23:17 UTC, merged